# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for Ruslan Desktop Agent.
Build: pyinstaller --noconfirm build.spec
"""

import sys
import os
from pathlib import Path

BLOCK_CIPHER = None

a = Analysis(
    ['core/main.py'],
    pathex=[os.path.dirname(__file__)],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('config', 'config'),
        ('plugins/*/manifest.json', 'plugins'),
    ],
    hiddenimports=[
        'core',
        'actions',
        'actions.engine',
        'api',
        'api.main',
        'brain',
        'brain.gateway',
        'voice',
        'voice.engine',
        'ui',
        'ui.overlay',
        'ui.chat_dialog',
        'ui.hotkey',
        'ui.drag_drop',
        'ui.sprite_widget',
        'macos',
        'macos.controller',
        'memory',
        'memory.store',
        'plugins',
        'plugins.manager',
        'pydantic',
        'pydantic_settings',
        'loguru',
        'anyio',
        'httpx',
        'uvicorn',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'PyQt5.QtWebEngine',
        'PyQt5.QtWebEngineWidgets',
        'PyQt5.QtWebKit',
        'PyQt5.QtWebKitWidgets',
        'PyQt5.QtMultimedia',
        'PyQt5.QtMultimediaWidgets',
        'PyQt5.QtPositioning',
        'PyQt5.QtLocation',
        'PyQt5.QtSensors',
        'PyQt5.QtTest',
        'PyQt5.QtXml',
        'PyQt5.QtXmlPatterns',
        'PyQt5.QtHelp',
        'PyQt5.QtNetwork',
        'PyQt5.QtBluetooth',
        'PyQt5.QtNfc',
        'PyQt5.QtSvg',
        'PyQt5.QtPrintSupport',
        'PyQt5.QtDesigner',
        'PyQt5.QtDBus',
        'notebook',
        'IPython',
        'matplotlib',
        'scipy',
        'pandas',
        'numpy',
        'cv2',
        'torch',
        'tensorflow',
        'transformers',
        'soundfile',
        'sounddevice',
        'PyQt5.uic',
        'PyQt5.uic.port_v2',
        'PyQt5.uic.port_v3',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=BLOCK_CIPHER)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Руслан',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/app_icon.icns',
)

app = BUNDLE(
    exe,
    name='Руслан.app',
    icon='assets/app_icon.icns',
    bundle_identifier='com.valldun1.ruslan-desktop',
    info_plist={
        'CFBundleShortVersionString': '0.2.1',
        'CFBundleVersion': '0.2.1',
        'CFBundleName': 'Руслан',
        'CFBundleDisplayName': 'Руслан Desktop Agent',
        'CFBundleExecutable': 'Руслан',
        'CFBundleIdentifier': 'com.valldun1.ruslan-desktop',
        'NSHighResolutionCapable': True,
        'NSHumanReadableCopyright': '© 2026 Valentin (kap@ruslan.team)',
        'LSMinimumSystemVersion': '10.13.0',
        'NSPrincipalClass': 'NSApplication',
        'LSUIElement': True,
        'NSAppleEventsUsageDescription': 'Руслан управляет окнами и приложениями.',
        'NSSystemAdministrationUsageDescription': 'Руслан требует доступ к управлению системой для горячих клавиш.',
        'NSAccessibilityUsageDescription': 'Руслан требует доступ к специальным возможностям для отслеживания окон.',
    },
)
